### ISSUE TITLE
Интерпретатор не проверяет значение переменной при парсинге

### ISSUE THREAD

**Issue by ghost** [zak0zak0/memsym#1]
![image](https://user-images.githubusercontent.com/1133957/116789850-ae027380-aab9-11eb-8c6e-bb4ba0889713.png)

Кроме проверки значения предлагаю включить знак присвоения в синтаксис, чтоб было привычнее.

**Comment by zak0zak0** [comment]
@Usievalad  исправлено с новым интерпретатором
